package org.fdapservice.phone;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "ITelephone", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
public interface ITelephone {

	/**
	 * 
	 * @param key
	 * @param callTimes
	 * @param phoneNumber
	 */
	@WebMethod(operationName = "Call", action = "http://www.thermoberg.com/Services/TelephoneService/ITelephone/Call")
	@RequestWrapper(localName = "Call", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.Call")
	@ResponseWrapper(localName = "CallResponse", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.CallResponse")
	public void call(
			@WebParam(name = "Key", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String key,
			@WebParam(name = "phoneNumber", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String phoneNumber,
			@WebParam(name = "CallTimes", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			Integer callTimes);

	/**
	 * 
	 * @param key
	 * @param message
	 * @param phoneNumber
	 */
	@WebMethod(operationName = "SendMessage", action = "http://www.thermoberg.com/Services/TelephoneService/ITelephone/SendMessage")
	@RequestWrapper(localName = "SendMessage", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.SendMessage")
	@ResponseWrapper(localName = "SendMessageResponse", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.SendMessageResponse")
	public void sendMessage(
			@WebParam(name = "key", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String key,
			@WebParam(name = "phoneNumber", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String phoneNumber,
			@WebParam(name = "message", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String message);

	/**
	 * 
	 * @param key
	 * @param phoneNumber
	 */
	@WebMethod(operationName = "StopCall", action = "http://www.thermoberg.com/Services/TelephoneService/ITelephone/StopCall")
	@RequestWrapper(localName = "StopCall", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.StopCall")
	@ResponseWrapper(localName = "StopCallResponse", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService", className = "org.fdapservice.phone.StopCallResponse")
	public void stopCall(
			@WebParam(name = "Key", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String key,
			@WebParam(name = "phoneNumber", targetNamespace = "http://www.thermoberg.com/Services/TelephoneService")
			String phoneNumber);

}
